config/routes.rb
Rails.application.routes.draw do

  resources :beer_clubs
  resources :users
  root 'breweries#index'
  get 'signup', to: 'users#new'
  get 'kaikki_bisset', to: 'beers#index'
  resources :ratings, only: [:index, :new, :create, :destroy]
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :beers
  resources :breweries
  resource :session, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ratebeer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  <div class="navibar">
	    <%= link_to 'breweries', breweries_path %>
	    <%= link_to 'beers', beers_path %>
	    <%= link_to 'ratings', ratings_path %>
      <%= link_to 'users', users_path %>
      <% if current_user %>
        <%= link_to current_user, current_user %>
      <% end %>  
      <% if current_user %>
        <%= link_to 'sign out', signout_path, :method => 'delete' %>
      <% else %>
        <%= link_to 'sign in', new_session_path %> 
        <%= link_to 'sign up', new_user_path %>
      <% end %>      
	  </div>
    <%= yield %>
  </body>

  <% if current_user %>
    <p><%= current_user.username %> signed in</p>
  <% end %>
  
  <% if session[:last_rating].nil? %>
    <p>no ratings given</p>
  <% else %>
    <p>previous rating: <%= session[:last_rating] %></p>
  <% end %>

</html>